### ISSUE TITLE
Enhancement: .exe file for the tkinter gui

### ISSUE THREAD

**Issue by sunchit17** [sunchit17/Snake-Game-Tkinter#1]
I am looking to convert the python script to an executable(.exe) file, tried using **pyinstaller** but to no avail.

**Comment by hjanday** [comment]
Can I help? Do you want to turn the script into an exe app?

**Comment by sunchit17** [comment]
Yes, you can take this up and yes I want to turn the script into an exe app, but pyinstaller is giving me a headache.

**Comment by sunchit17** [comment]
@hjanday Are you still working on it?

**Comment by hjanday** [comment]
I was, pyinstaller is bugging out for my machine too

**Comment by sunchit17** [comment]
No problem, I'd have to check with the cx_freeze thingy as suggested in a different PR to this repo. You can check that out too. Thanks for taking out time tho :D
